"""AI step plumbing: choosing files, batching, and merging answers.

No AI is called here: the tests play the part of the agent by writing the
JSON answer themselves.
"""

import json
import os
import unittest

from reposage import summarize
from tests.helpers import copy_fixture, node, scan


def plan_for(repo, **kw):
    graph, _ = scan(repo)
    return summarize.plan(repo, graph, **kw)


def answer_for(p, batch_no, layer="Service"):
    """A well-formed agent answer for every file and symbol in a batch."""
    batch = next(b for b in p["batches"] if b["batch"] == batch_no)
    return json.dumps({"batch": batch_no, "files": [
        {"path": f["path"], "summary": f"Does things in {f['path']}.", "layer": layer,
         "tags": ["Shop Logic", "orders"],
         "symbols": [{"id": s, "summary": "Does one thing."} for s in f["symbols"]]}
        for f in batch["files"]]})


def graph_of(repo):
    with open(os.path.join(repo, ".reposage", "graph.json"), encoding="utf-8") as f:
        return json.load(f)


class PlanTest(unittest.TestCase):
    def test_skips_tests_and_generated_and_trivial(self):
        repo = copy_fixture("py_project")
        os.makedirs(os.path.join(repo, "tests"))
        with open(os.path.join(repo, "tests", "test_shop.py"), "w") as f:
            f.write("def test_x():\n    assert 1\n")
        with open(os.path.join(repo, "shop", "api_pb2.py"), "w") as f:
            f.write("# Generated by the protocol buffer compiler.  DO NOT EDIT!\nX = 1\ndef f():\n    return X\n")
        p = plan_for(repo)
        planned = {f["path"] for b in p["batches"] for f in b["files"]}
        self.assertEqual(planned, {"shop/models.py", "shop/services.py", "shop/utils.py"})
        self.assertEqual(p["skipped"]["tests"], ["tests/test_shop.py"])
        self.assertEqual(p["skipped"]["generated"], ["shop/api_pb2.py"])
        # The docstring-only __init__.py gets a fixed summary, no AI.
        self.assertEqual(p["rule_based"], ["shop/__init__.py"])
        self.assertIn("Python package", node(graph_of(repo), "shop/__init__.py")["summary"])

    def test_include_tests_and_limit(self):
        repo = copy_fixture("js_project")
        with open(os.path.join(repo, "src", "api.test.ts"), "w") as f:
            f.write("import { Api } from './api';\n\nfunction checkFetch() {\n  return new Api().fetchUser(1);\n}\n\ntest('fetch', checkFetch);\n")
        p = plan_for(repo, limit=2)
        # legacy.cjs is 3 lines with no functions -> fixed summary, not AI.
        self.assertEqual(p["rule_based"], ["src/legacy.cjs"])
        self.assertEqual(p["files_to_summarize"], 2)
        self.assertEqual(len(p["skipped"]["over limit"]), 3)
        self.assertEqual(p["skipped"]["tests"], ["src/api.test.ts"])
        p = plan_for(repo, include_tests=True)
        self.assertIn("src/api.test.ts", [f["path"] for b in p["batches"] for f in b["files"]])

    def test_batch_file_contents(self):
        repo = copy_fixture("java_project")
        p = plan_for(repo)
        with open(os.path.join(repo, p["batches"][0]["file"]), encoding="utf-8") as f:
            text = f.read()
        self.assertIn("## File: src/main/java/com/shop/service/OrderService.java", text)
        self.assertIn("id: `src/main/java/com/shop/service/OrderService.java::OrderService.place`", text)
        self.assertIn("repo.save(order);", text)                   # the source itself
        self.assertGreater(p["estimated_input_tokens"], 500)


class SaveTest(unittest.TestCase):
    def test_merges_and_survives_rescan(self):
        repo = copy_fixture("py_project")
        p = plan_for(repo)
        files, symbols, problems = summarize.save(repo, 1, "```json\n" + answer_for(p, 1) + "\n```")
        self.assertEqual((files, problems), (3, []))
        self.assertGreater(symbols, 0)
        g = graph_of(repo)
        self.assertEqual(node(g, "shop/models.py")["layer"], "Service")
        self.assertEqual(node(g, "shop/models.py")["tags"], ["shop-logic", "orders"])
        self.assertEqual(summarize.progress(repo), (3, 3))

        # Re-scan: unchanged files keep their summaries...
        g, _ = scan(repo)
        self.assertTrue(node(g, "shop/models.py")["summary"])
        # ...and the next plan has nothing left to do.
        self.assertEqual(plan_for(repo)["files_to_summarize"], 0)

    def test_changed_file_is_summarized_again(self):
        repo = copy_fixture("py_project")
        summarize.save(repo, 1, answer_for(plan_for(repo), 1))
        with open(os.path.join(repo, "shop", "utils.py"), "a") as f:
            f.write("\n\ndef shout(t):\n    return t.upper()\n")
        p = plan_for(repo)
        self.assertEqual([f["path"] for b in p["batches"] for f in b["files"]], ["shop/utils.py"])
        self.assertTrue(node(graph_of(repo), "shop/utils.py")["ai_stale"])     # old summary kept, flagged
        summarize.save(repo, 1, answer_for(p, 1))
        self.assertNotIn("ai_stale", node(graph_of(repo), "shop/utils.py"))   # fresh again

    def test_bad_answers_are_reported_not_fatal(self):
        repo = copy_fixture("py_project")
        p = plan_for(repo)
        self.assertEqual(summarize.save(repo, 1, "sorry, I can't")[0], 0)
        self.assertEqual(summarize.save(repo, 9, answer_for(p, 1))[2],
                         ["there is no batch 9 in the current plan"])
        data = json.loads(answer_for(p, 1, layer="Backend"))
        data["files"] = data["files"][:2]                       # one file missing
        files, _, problems = summarize.save(repo, 1, json.dumps(data))
        self.assertEqual(files, 2)
        self.assertTrue(any("not one of" in x for x in problems))  # bad layer: guess kept
        self.assertTrue(any("missing from the answer" in x for x in problems))
        self.assertIsNone(node(graph_of(repo), "shop/models.py")["layer"])  # "Backend" rejected

    def test_stale_file_is_not_overwritten(self):
        repo = copy_fixture("py_project")
        p = plan_for(repo)
        with open(os.path.join(repo, "shop", "utils.py"), "a") as f:
            f.write("\n# edited after planning\n")
        scan(repo)                                             # graph now has the new hash
        files, _, problems = summarize.save(repo, 1, answer_for(p, 1))
        self.assertEqual(files, 2)
        self.assertTrue(any("changed since the plan" in x for x in problems))

    def test_ai_layer_reaches_dashboard(self):
        from reposage.dashboard.build import build_data
        repo = copy_fixture("py_project")
        summarize.save(repo, 1, answer_for(plan_for(repo), 1, layer="Data"))
        d = build_data(graph_of(repo), repo)
        i = d["files"]["path"].index("shop/services.py")
        self.assertEqual(d["groups"][d["files"]["group"][i]], "Data")   # AI beats the "Service" guess
        self.assertEqual(d["files"]["tags"][i], ["shop-logic", "orders"])


class RunTest(unittest.TestCase):
    """`summarize run` with a fake `claude` program."""

    def setUp(self):
        import shutil, stat, tempfile
        self.tmp = tempfile.mkdtemp(prefix="reposage-fake-")
        fake = os.path.join(self.tmp, "claude")
        shutil.copy(os.path.join(os.path.dirname(__file__), "fake_claude.py"), fake)
        os.chmod(fake, os.stat(fake).st_mode | stat.S_IEXEC)
        self.env = {"REPOSAGE_CLAUDE": fake, "FAKE_CLAUDE_DIR": self.tmp}
        self.old = {k: os.environ.get(k) for k in list(self.env) + ["FAKE_CLAUDE_MODE"]}
        os.environ.update(self.env)

    def tearDown(self):
        for k, v in self.old.items():
            if v is None:
                os.environ.pop(k, None)
            else:
                os.environ[k] = v

    def test_run_summarizes_every_batch(self):
        repo = copy_fixture("java_project")
        plan_for(repo)
        lines = []
        totals = summarize.run(repo, parallel=3, say=lines.append)
        self.assertEqual(totals["failed"], [])
        self.assertEqual(summarize.progress(repo), (7, 7))
        g = graph_of(repo)
        place = node(g, "src/main/java/com/shop/service/OrderService.java::OrderService.place")
        self.assertEqual(place["summary"], "Does one step of the work.")
        self.assertIn("Cost of this run: $0.00", lines[-1])
        # Running again has nothing left to do.
        self.assertEqual(summarize.run(repo, say=lambda m: None)["batches"], 0)

    def test_retries_a_bad_answer_once(self):
        os.environ["FAKE_CLAUDE_MODE"] = "flaky"
        repo = copy_fixture("py_project")
        plan_for(repo)
        totals = summarize.run(repo, say=lambda m: None)
        self.assertEqual(totals["failed"], [])
        self.assertEqual(summarize.progress(repo), (3, 3))
        self.assertAlmostEqual(totals["cost_usd"], 0.003)   # the bad call is counted too

    def test_missing_claude_is_explained(self):
        os.environ["REPOSAGE_CLAUDE"] = ""
        import shutil as sh
        if sh.which("claude"):
            self.skipTest("a real `claude` is installed here")
        repo = copy_fixture("py_project")
        plan_for(repo)
        with self.assertRaisesRegex(RuntimeError, "claude"):
            summarize.run(repo, say=lambda m: None)


class SaveCommandTest(unittest.TestCase):
    def test_cli_reads_answer_file_written_by_agent(self):
        import contextlib, io
        from reposage.__main__ import main
        repo = copy_fixture("py_project")
        p = plan_for(repo)
        with open(os.path.join(repo, ".reposage", "ai", "answer-001.json"), "w", encoding="utf-8") as f:
            f.write(answer_for(p, 1))
        out = io.StringIO()
        with contextlib.redirect_stdout(out):
            self.assertEqual(main(["summarize", "save", "1", repo]), 0)
        self.assertIn("Progress: 3 of 3", out.getvalue())
        # --yes is accepted (the skill passes its arguments through)
        with contextlib.redirect_stdout(io.StringIO()):
            self.assertEqual(main(["summarize", "plan", repo, "--yes"]), 0)


if __name__ == "__main__":
    unittest.main()
