"""The AI step: plain-English summaries, real layers and tags.

Tree-sitter tells us WHAT is in the code (deterministic facts). This step
adds WHY: a short plain-English summary for each file and its key
functions, the file's architectural layer, and a few topic tags.

The writing is done by Claude (a small, cheap model) following the
instructions in agents/summarizer.md. This module does everything around it:

  plan  -> choose which files need a summary, pack them into batches
           (.reposage/ai/batch-001.md, ...) and estimate the size of the job
  run   -> send each batch to `claude -p` (Haiku, no tools), a few at a
           time, and save every answer as soon as it arrives
  save  -> check one batch's answer (JSON) and merge it into graph.json

Being affordable:
  * incremental: a file is only summarized again when its content changed
    (summaries are kept per file hash; see graph_builder._carry_over_ai_fields)
  * tests and generated code are skipped by default
  * near-empty files get a fixed summary without asking the AI
  * files are batched, and a cheap model (Haiku) does the writing
"""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import threading
import time
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import Callable, Optional

from .cache import write_json_atomic
from .layers import LAYERS, TESTS, guess_layer

AI_DIR = "ai"
BATCH_CHARS = 45_000          # ~11k tokens of input per batch
MAX_FILES_PER_BATCH = 10
SOURCE_CHARS = 9_000          # per file: the first ~250 lines of code
MAX_KEY_SYMBOLS = 6           # per file
SUMMARY_LIMIT = 700           # characters, file summaries
SYMBOL_SUMMARY_LIMIT = 300
MAX_TAGS = 4

_GENERATED_DIRS = {"generated", "__generated__", "gen", "vendor", "vendors",
                   "third_party", "thirdparty", "external", "migrations"}
_GENERATED_NAME = re.compile(r"(_pb2(_grpc)?\.py|\.pb\.\w+|\.generated\.\w+|\.g\.\w+|"
                             r"\.min\.js|\.bundle\.js)$", re.I)
_GENERATED_HEADER = re.compile(r"auto-?generated|@generated|do not edit|generated by", re.I)


# ----------------------------------------------------------------------
# plan
# ----------------------------------------------------------------------

def plan(repo: str, graph: dict, include_tests: bool = False, force: bool = False,
         limit: Optional[int] = None) -> dict:
    """Decide what to summarize, write the batch files, return the plan."""
    nodes = graph["nodes"]
    files = [n for n in nodes if n["type"] == "file"]
    symbols_by_file: dict[str, list[dict]] = defaultdict(list)
    for n in nodes:
        if n["type"] != "file":
            symbols_by_file[n["path"]].append(n)
    degree = _degrees(graph)
    links = _file_links(graph)

    todo, skipped = [], defaultdict(list)
    rule_based: dict[str, str] = {}
    for f in files:
        path = f["id"]
        if f.get("summary") and not f.get("ai_stale") and not force:
            skipped["done"].append(path)
            continue
        if guess_layer(path) == TESTS and not include_tests:
            skipped["tests"].append(path)
            continue
        source = _read(os.path.join(repo, path))
        if source is None:
            skipped["unreadable"].append(path)
            continue
        if _is_generated(path, source):
            skipped["generated"].append(path)
            continue
        trivial = _trivial_summary(path, source, symbols_by_file[path])
        if trivial:
            rule_based[path] = trivial
            continue
        todo.append(f)

    # Most connected files first, so `--limit` keeps the important ones.
    todo.sort(key=lambda f: (-degree.get(f["id"], 0), f["id"]))
    if limit is not None and len(todo) > limit:
        skipped["over limit"] = [f["id"] for f in todo[limit:]]
        todo = todo[:limit]

    # Build one text section per file, then pack sections into batches.
    sections = []
    for f in todo:
        path = f["id"]
        keys = _key_symbols(symbols_by_file[path], degree)
        text = _file_section(repo, f, graph, keys, links)
        sections.append({"path": path, "hash": graph["files"][path]["hash"],
                         "symbols": [s["id"] for s in keys], "text": text})

    batches, current, size = [], [], 0
    for sec in sections:
        if current and (size + len(sec["text"]) > BATCH_CHARS
                        or len(current) >= MAX_FILES_PER_BATCH):
            batches.append(current)
            current, size = [], 0
        current.append(sec)
        size += len(sec["text"])
    if current:
        batches.append(current)

    # Write the batches.
    ai_dir = os.path.join(repo, ".reposage", AI_DIR)
    shutil.rmtree(ai_dir, ignore_errors=True)
    os.makedirs(ai_dir)
    project = os.path.basename(os.path.abspath(repo))
    batch_meta = []
    for k, batch in enumerate(batches, start=1):
        name = f"batch-{k:03d}.md"
        header = (f"# RepoSage summary batch {k} of {len(batches)}\n\n"
                  f"Project: **{project}**. Summarize the {len(batch)} file(s) below "
                  f"and answer with ONE JSON object, as described in your instructions. "
                  f"Use `\"batch\": {k}`.\n")
        with open(os.path.join(ai_dir, name), "w", encoding="utf-8", newline="\n") as fh:
            fh.write(header + "\n".join(sec["text"] for sec in batch))
        batch_meta.append({"batch": k, "file": f".reposage/{AI_DIR}/{name}",
                           "files": [{"path": s["path"], "hash": s["hash"], "symbols": s["symbols"]}
                                     for s in batch]})

    # Near-empty files: apply their fixed summary right away.
    if rule_based:
        _merge(repo, {p: {"summary": s} for p, s in rule_based.items()})

    total_chars = sum(len(s["text"]) for s in sections)
    n_symbols = sum(len(s["symbols"]) for s in sections)
    result = {
        "batches": batch_meta,
        "files_to_summarize": len(sections),
        "symbols_to_summarize": n_symbols,
        "rule_based": sorted(rule_based),
        "skipped": {k: sorted(v) for k, v in skipped.items()},
        # ~4 characters per token; plus the agent's instructions for each batch.
        "estimated_input_tokens": total_chars // 4 + 1_200 * len(batches),
        "estimated_output_tokens": 130 * len(sections) + 45 * n_symbols,
    }
    write_json_atomic(os.path.join(ai_dir, "plan.json"), result)
    return result


def print_plan(p: dict) -> None:
    skipped = p["skipped"]
    print("RepoSage summarize: plan")
    print(f"  To summarize   {p['files_to_summarize']} files "
          f"(+ {p['symbols_to_summarize']} key functions/classes) "
          f"in {len(p['batches'])} batch{'es' if len(p['batches']) != 1 else ''}")
    print(f"  Already done   {len(skipped.get('done', []))} files (unchanged since their last summary)")
    parts = [f"{len(skipped.get('tests', []))} test files",
             f"{len(skipped.get('generated', []))} generated/vendored"]
    if skipped.get("over limit"):
        parts.append(f"{len(skipped['over limit'])} over --limit")
    print(f"  Skipped        {', '.join(parts)}")
    if p["rule_based"]:
        print(f"  Near-empty     {len(p['rule_based'])} files got a fixed summary (no AI needed)")
    print(f"  Estimated size ~{p['estimated_input_tokens']:,} input + "
          f"~{p['estimated_output_tokens']:,} output tokens (Haiku agents)")
    for b in p["batches"]:
        print(f"  Batch {b['batch']:>3}      {b['file']}  ({len(b['files'])} files)")
    if not p["batches"]:
        print("  Nothing to do: every file already has an up-to-date summary.")


# ----------------------------------------------------------------------
# save
# ----------------------------------------------------------------------

def save(repo: str, batch_no: int, answer: str) -> tuple[int, int, list[str]]:
    """Check an agent's answer for one batch and merge it into graph.json.

    Returns (files saved, symbols saved, problems). Problems are reported so
    the batch can be retried; the good parts of an answer are always kept.
    """
    plan_path = os.path.join(repo, ".reposage", AI_DIR, "plan.json")
    with open(plan_path, encoding="utf-8") as fh:
        the_plan = json.load(fh)
    batch = next((b for b in the_plan["batches"] if b["batch"] == batch_no), None)
    if batch is None:
        return 0, 0, [f"there is no batch {batch_no} in the current plan"]
    try:
        data = json.loads(_strip_fences(answer))
    except ValueError as e:
        return 0, 0, [f"the answer is not valid JSON ({e})"]
    if not isinstance(data, dict) or not isinstance(data.get("files"), list):
        return 0, 0, ['expected an object like {"batch": N, "files": [...]}']

    expected = {f["path"]: f for f in batch["files"]}
    updates: dict[str, dict] = {}
    problems: list[str] = []
    answered: set[str] = set()      # files the answer mentioned (even if invalid)
    n_symbols = 0
    for item in data["files"]:
        if not isinstance(item, dict):
            continue
        path = item.get("path")
        if path not in expected:
            problems.append(f"unknown file in answer: {path!r}")
            continue
        answered.add(path)
        summary = _clean_text(item.get("summary"), SUMMARY_LIMIT)
        if not summary:
            problems.append(f"{path}: empty summary")
            continue
        layer = item.get("layer")
        if layer not in LAYERS:
            problems.append(f"{path}: layer {layer!r} is not one of {', '.join(LAYERS)}; kept the guess")
            layer = None
        tags = [re.sub(r"[^a-z0-9+#.-]+", "-", str(t).lower()).strip("-")
                for t in (item.get("tags") or []) if str(t).strip()][:MAX_TAGS]
        update = {"summary": summary, "tags": tags, "hash": expected[path]["hash"]}
        if layer:
            update["layer"] = layer
        allowed = set(expected[path]["symbols"])
        sym_updates = {}
        for sym in item.get("symbols") or []:
            if isinstance(sym, dict) and sym.get("id") in allowed:
                text = _clean_text(sym.get("summary"), SYMBOL_SUMMARY_LIMIT)
                if text:
                    sym_updates[sym["id"]] = text
        update["symbols"] = sym_updates
        n_symbols += len(sym_updates)
        updates[path] = update
    missing = sorted(set(expected) - answered)
    problems += [f"{p}: missing from the answer" for p in missing]

    saved, stale = _merge(repo, updates)
    problems += [f"{p}: file changed since the plan; run the plan again" for p in stale]
    return saved, n_symbols, problems


def progress(repo: str) -> tuple[int, int]:
    """(files in the plan that now have a summary, files in the plan)."""
    with open(os.path.join(repo, ".reposage", AI_DIR, "plan.json"), encoding="utf-8") as fh:
        the_plan = json.load(fh)
    planned = {f["path"] for b in the_plan["batches"] for f in b["files"]}
    graph = _load_graph(repo)
    done = sum(1 for n in graph["nodes"] if n["id"] in planned and n.get("summary"))
    return done, len(planned)


# ----------------------------------------------------------------------
# run
# ----------------------------------------------------------------------

AGENT_PROMPT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                            "agents", "summarizer.md")


def run(repo: str, model: str = "haiku", parallel: int = 4, timeout: int = 300,
        say: Callable[[str], None] = print) -> dict:
    """Summarize every batch of the current plan that isn't saved yet.

    Each batch goes to a separate `claude -p` process: no tools, a short
    system prompt (agents/summarizer.md), the batch as the message. Answers
    are saved as they arrive, so an interrupted run can simply be started
    again and continues where it stopped.
    """
    claude = os.environ.get("REPOSAGE_CLAUDE") or shutil.which("claude")
    if not claude:
        raise RuntimeError("the `claude` command was not found. RepoSage uses Claude Code "
                           "to write summaries; install it from https://claude.com/claude-code")
    with open(os.path.join(repo, ".reposage", AI_DIR, "plan.json"), encoding="utf-8") as fh:
        the_plan = json.load(fh)
    system_prompt = _agent_instructions()
    todo = [b for b in the_plan["batches"] if not _batch_done(repo, b)]
    if not todo:
        say("All batches are already saved.")
        return {"batches": 0, "files": 0, "symbols": 0, "cost_usd": 0.0, "failed": []}

    def ask(batch: dict) -> tuple[str, float]:
        with open(os.path.join(repo, batch["file"]), encoding="utf-8") as fh:
            message = fh.read()
        proc = subprocess.run(
            [claude, "-p", "--model", model, "--tools", "", "--output-format", "json",
             "--system-prompt", system_prompt, "--no-session-persistence",
             "--strict-mcp-config", "--disable-slash-commands"],
            input=message, capture_output=True, text=True, timeout=timeout)
        try:
            out = json.loads(proc.stdout)
        except ValueError:
            raise RuntimeError((proc.stderr or proc.stdout or "no output").strip()[:300])
        if out.get("is_error"):
            raise RuntimeError(str(out.get("result"))[:300])
        return out.get("result", ""), float(out.get("total_cost_usd") or 0)

    totals = {"batches": 0, "files": 0, "symbols": 0, "cost_usd": 0.0, "failed": []}
    total_batches = len(the_plan["batches"])
    graph_lock = threading.Lock()      # one writer of graph.json at a time

    def work(batch: dict) -> tuple[dict, int, int, list[str], float, float]:
        started, cost, problems = time.time(), 0.0, []
        files = symbols = 0
        for attempt in (1, 2):                        # one retry if something is missing
            try:
                answer, c = ask(batch)
                cost += c
                with graph_lock:
                    f, s_, problems = save(repo, batch["batch"], answer)
                files, symbols = files + f, symbols + s_
            except (RuntimeError, subprocess.TimeoutExpired, OSError) as e:
                problems = [f"Claude call failed: {e}"]
            with graph_lock:
                if _batch_done(repo, batch):
                    break
        return batch, files, symbols, problems, cost, time.time() - started

    say(f"Summarizing {len(todo)} batch(es) with {model}, {min(parallel, len(todo))} at a time...")
    with ThreadPoolExecutor(max_workers=max(1, parallel)) as pool:
        futures = [pool.submit(work, b) for b in todo]
        for fut in as_completed(futures):
            batch, files, symbols, problems, cost, secs = fut.result()
            ok = _batch_done(repo, batch)
            totals["batches"] += 1
            totals["files"] += files
            totals["symbols"] += symbols
            totals["cost_usd"] += cost
            say(f"  batch {batch['batch']}/{total_batches}: {files} files, {symbols} functions/classes"
                f" {'✓' if ok else '(incomplete)'}  ${cost:.3f}, {secs:.0f}s")
            if not ok:
                totals["failed"].append(batch["batch"])
                for p in problems[:5]:
                    say(f"      problem: {p}")
    done, planned = progress(repo)
    say(f"Done: {done} of {planned} planned files have a summary. "
        f"Cost of this run: ${totals['cost_usd']:.2f}.")
    if totals["failed"]:
        say(f"Incomplete batches: {totals['failed']}. Run `summarize run` again to retry them.")
    return totals


def _agent_instructions() -> str:
    """The body of agents/summarizer.md (without its frontmatter)."""
    with open(AGENT_PROMPT, encoding="utf-8") as fh:
        text = fh.read()
    if text.startswith("---"):
        text = text.split("---", 2)[2]
    return text.strip()


def _batch_done(repo: str, batch: dict) -> bool:
    """True when every file of the batch has a summary for its planned hash."""
    graph = _load_graph(repo)
    by_id = {n["id"]: n for n in graph["nodes"]}
    for f in batch["files"]:
        node = by_id.get(f["path"])
        if (node is None or not node.get("summary") or node.get("ai_stale")
                or graph["files"].get(f["path"], {}).get("hash") != f["hash"]):
            return False
    return True


# ----------------------------------------------------------------------
# Helpers
# ----------------------------------------------------------------------

def _merge(repo: str, updates: dict[str, dict]) -> tuple[int, list[str]]:
    """Write summaries into graph.json. Skips files whose hash moved on."""
    graph = _load_graph(repo)
    by_id = {n["id"]: n for n in graph["nodes"]}
    saved, stale = 0, []
    for path, up in updates.items():
        node = by_id.get(path)
        if node is None or ("hash" in up and graph["files"].get(path, {}).get("hash") != up["hash"]):
            stale.append(path)
            continue
        node["summary"] = up["summary"]
        node.pop("ai_stale", None)                 # fresh again
        if "layer" in up:
            node["layer"] = up["layer"]
        if "tags" in up:
            node["tags"] = up["tags"]
        for sym_id, text in up.get("symbols", {}).items():
            if sym_id in by_id:
                by_id[sym_id]["summary"] = text
                by_id[sym_id].pop("ai_stale", None)
        saved += 1
    write_json_atomic(os.path.join(repo, ".reposage", "graph.json"), graph)
    return saved, stale


def _load_graph(repo: str) -> dict:
    with open(os.path.join(repo, ".reposage", "graph.json"), encoding="utf-8") as fh:
        return json.load(fh)


def _read(path: str) -> Optional[str]:
    try:
        with open(path, encoding="utf-8", errors="replace") as fh:
            return fh.read()
    except OSError:
        return None


def _is_generated(path: str, source: str) -> bool:
    parts = path.lower().split("/")
    if any(p in _GENERATED_DIRS for p in parts[:-1]) or _GENERATED_NAME.search(parts[-1]):
        return True
    head = "\n".join(source.splitlines()[:5])
    return bool(_GENERATED_HEADER.search(head))


def _trivial_summary(path: str, source: str, symbols: list[dict]) -> Optional[str]:
    """A fixed summary for files with (almost) nothing in them."""
    lines = [ln for ln in source.splitlines()
             if ln.strip() and not ln.strip().startswith(("#", "//", "/*", "*"))]
    if symbols or len(lines) > 3:
        return None
    name = path.rsplit("/", 1)[-1]
    if name == "__init__.py":
        return ("Marks this folder as a Python package so its files can be imported."
                + (" It also re-exports a few names for convenience." if lines else ""))
    if not lines:
        return "An empty file (it may only contain comments)."
    return f"A very small file with {len(lines)} line(s) of setup code."


def _degrees(graph: dict) -> dict[str, int]:
    """Number of calls/imports touching each node (and each file)."""
    deg: dict[str, int] = defaultdict(int)
    for e in graph["edges"]:
        if e["type"] in ("calls", "imports"):
            deg[e["source"]] += 1
            deg[e["target"]] += 1
            fs, ft = e["source"].split("::")[0], e["target"].split("::")[0]
            if e["type"] == "calls" and fs != ft:
                deg[fs] += 1
                deg[ft] += 1
    return deg


def _file_links(graph: dict) -> dict[str, dict[str, set]]:
    uses: dict[str, set] = defaultdict(set)
    used_by: dict[str, set] = defaultdict(set)
    for e in graph["edges"]:
        if e["type"] in ("calls", "imports"):
            s, t = e["source"].split("::")[0], e["target"].split("::")[0]
            if s != t:
                uses[s].add(t)
                used_by[t].add(s)
    return {"uses": uses, "used_by": used_by}


def _key_symbols(symbols: list[dict], degree: dict[str, int]) -> list[dict]:
    """The few classes/functions worth a one-line summary."""
    def score(s: dict) -> tuple:
        private = s["name"].startswith("_") and not s["name"].startswith("__")
        size = s["end_line"] - s["start_line"] + 1
        top_level = 8 if s.get("parent") is None else 0
        return (-(degree.get(s["id"], 0) * 3 + top_level + (5 if s["type"] in ("class", "interface") else 0)
                  + min(size, 60) / 10 - (6 if private else 0)), s["id"])
    candidates = [s for s in symbols
                  if s["end_line"] - s["start_line"] >= 2 or degree.get(s["id"], 0) >= 2]
    return sorted(candidates, key=score)[:MAX_KEY_SYMBOLS]


def _file_section(repo: str, f: dict, graph: dict, keys: list[dict], links: dict) -> str:
    path = f["id"]
    source = _read(os.path.join(repo, path)) or ""
    lines = source.splitlines()
    shown = source[:SOURCE_CHARS]
    cut = len(shown) < len(source)
    if cut:
        shown = shown[: shown.rfind("\n")]
    shown_lines = shown.count("\n") + 1
    outline = sorted((n for n in graph["nodes"] if n.get("path") == path and n["type"] != "file"),
                     key=lambda n: (n["start_line"], n["id"]))
    fence = "~~~~"      # can't clash with ``` inside the code

    def names(paths: set) -> str:
        items = sorted(p.rsplit("/", 1)[-1] for p in paths)
        return ", ".join(items[:12]) + (f" (+{len(items) - 12} more)" if len(items) > 12 else "") or "none"

    out = [f"\n## File: {path}",
           f"- language: {f.get('language')}, {len(lines)} lines",
           f"- layer guessed from its path: {guess_layer(path)}",
           f"- uses: {names(links['uses'].get(path, set()))}",
           f"- used by: {names(links['used_by'].get(path, set()))}"]
    if f.get("external_imports"):
        out.append(f"- external packages: {', '.join(f['external_imports'][:15])}")
    if keys:
        out.append("- key symbols to summarize (copy each id exactly):")
        out += [f"  - id: `{s['id']}` ({s['type']}, line {s['start_line']}): `{s['signature']}`" for s in keys]
    if cut:
        out.append(f"- outline of the whole file ({len(outline)} definitions):")
        out += [f"  - line {s['start_line']}: {s['type']} {s['name']}" for s in outline[:60]]
        out.append(f"\nSource (first {shown_lines} of {len(lines)} lines):")
    else:
        out.append("\nSource:")
    out += [fence, shown, fence]
    return "\n".join(out) + "\n"


def _strip_fences(text: str) -> str:
    text = text.strip()
    m = re.search(r"```(?:json)?\s*(\{.*\})\s*```", text, re.S)
    if m:
        return m.group(1)
    start, end = text.find("{"), text.rfind("}")
    return text[start:end + 1] if start != -1 and end > start else text


def _clean_text(value, limit: int) -> str:
    if not isinstance(value, str):
        return ""
    text = " ".join(value.split())
    return text if len(text) <= limit else text[: limit - 1].rstrip() + "…"
